import { useState } from "react";
import Modal from "../components/Modal";
import Button from "../components/Button";

function ModalPage() {
  const [showModal, setShowModal] = useState(false);

  const handleClick = () => {
    setShowModal(true);
  };

  const handleClose = () => {
    setShowModal(false);
  };

  const actionBar = <div><Button onClick={handleClose} primary>I accept</Button></div>
  const modal = <Modal onClose={handleClose} actionBar={actionBar}>
    <p>
        Here is an important agreement for you to accept
    </p>

  </Modal>

  return (
    <div>
      <Button onClick={handleClick} primary>
        Open Modal
      </Button>
      {showModal && modal}
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque justo nisi, elementum iaculis ornare eu, sodales non turpis. Cras quis orci non enim rhoncus facilisis. Etiam porttitor, lorem nec lacinia tincidunt, arcu felis lacinia enim, eget dapibus metus ante eu nisl. Quisque orci odio, interdum eu est sed, efficitur consectetur justo. Etiam ultrices, ligula ut feugiat aliquam, sem elit accumsan massa, a elementum ligula mi sed magna. Etiam et pharetra risus. Nullam a sapien tristique, blandit enim commodo, dictum justo. Fusce nec auctor massa. Sed luctus vitae felis vel imperdiet. Donec fringilla enim hendrerit, rhoncus erat in, posuere ligula. Maecenas hendrerit massa magna, pellentesque lobortis enim tristique non. Integer mollis quam id dictum interdum. Donec euismod mi quis ullamcorper dapibus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque justo nisi, elementum iaculis ornare eu, sodales non turpis. Cras quis orci non enim rhoncus facilisis. Etiam porttitor, lorem nec lacinia tincidunt, arcu felis lacinia enim, eget dapibus metus ante eu nisl. Quisque orci odio, interdum eu est sed, efficitur consectetur justo. Etiam ultrices, ligula ut feugiat aliquam, sem elit accumsan massa, a elementum ligula mi sed magna. Etiam et pharetra risus. Nullam a sapien tristique, blandit enim commodo, dictum justo. Fusce nec auctor massa. Sed luctus vitae felis vel imperdiet. Donec fringilla enim hendrerit, rhoncus erat in, posuere ligula. Maecenas hendrerit massa magna, pellentesque lobortis enim tristique non. Integer mollis quam id dictum interdum. Donec euismod mi quis ullamcorper dapibus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque justo nisi, elementum iaculis ornare eu, sodales non turpis. Cras quis orci non enim rhoncus facilisis. Etiam porttitor, lorem nec lacinia tincidunt, arcu felis lacinia enim, eget dapibus metus ante eu nisl. Quisque orci odio, interdum eu est sed, efficitur consectetur justo. Etiam ultrices, ligula ut feugiat aliquam, sem elit accumsan massa, a elementum ligula mi sed magna. Etiam et pharetra risus. Nullam a sapien tristique, blandit enim commodo, dictum justo. Fusce nec auctor massa. Sed luctus vitae felis vel imperdiet. Donec fringilla enim hendrerit, rhoncus erat in, posuere ligula. Maecenas hendrerit massa magna, pellentesque lobortis enim tristique non. Integer mollis quam id dictum interdum. Donec euismod mi quis ullamcorper dapibus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque justo nisi, elementum iaculis ornare eu, sodales non turpis. Cras quis orci non enim rhoncus facilisis. Etiam porttitor, lorem nec lacinia tincidunt, arcu felis lacinia enim, eget dapibus metus ante eu nisl. Quisque orci odio, interdum eu est sed, efficitur consectetur justo. Etiam ultrices, ligula ut feugiat aliquam, sem elit accumsan massa, a elementum ligula mi sed magna. Etiam et pharetra risus. Nullam a sapien tristique, blandit enim commodo, dictum justo. Fusce nec auctor massa. Sed luctus vitae felis vel imperdiet. Donec fringilla enim hendrerit, rhoncus erat in, posuere ligula. Maecenas hendrerit massa magna, pellentesque lobortis enim tristique non. Integer mollis quam id dictum interdum. Donec euismod mi quis ullamcorper dapibus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque justo nisi, elementum iaculis ornare eu, sodales non turpis. Cras quis orci non enim rhoncus facilisis. Etiam porttitor, lorem nec lacinia tincidunt, arcu felis lacinia enim, eget dapibus metus ante eu nisl. Quisque orci odio, interdum eu est sed, efficitur consectetur justo. Etiam ultrices, ligula ut feugiat aliquam, sem elit accumsan massa, a elementum ligula mi sed magna. Etiam et pharetra risus. Nullam a sapien tristique, blandit enim commodo, dictum justo. Fusce nec auctor massa. Sed luctus vitae felis vel imperdiet. Donec fringilla enim hendrerit, rhoncus erat in, posuere ligula. Maecenas hendrerit massa magna, pellentesque lobortis enim tristique non. Integer mollis quam id dictum interdum. Donec euismod mi quis ullamcorper dapibus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque justo nisi, elementum iaculis ornare eu, sodales non turpis. Cras quis orci non enim rhoncus facilisis. Etiam porttitor, lorem nec lacinia tincidunt, arcu felis lacinia enim, eget dapibus metus ante eu nisl. Quisque orci odio, interdum eu est sed, efficitur consectetur justo. Etiam ultrices, ligula ut feugiat aliquam, sem elit accumsan massa, a elementum ligula mi sed magna. Etiam et pharetra risus. Nullam a sapien tristique, blandit enim commodo, dictum justo. Fusce nec auctor massa. Sed luctus vitae felis vel imperdiet. Donec fringilla enim hendrerit, rhoncus erat in, posuere ligula. Maecenas hendrerit massa magna, pellentesque lobortis enim tristique non. Integer mollis quam id dictum interdum. Donec euismod mi quis ullamcorper dapibus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque justo nisi, elementum iaculis ornare eu, sodales non turpis. Cras quis orci non enim rhoncus facilisis. Etiam porttitor, lorem nec lacinia tincidunt, arcu felis lacinia enim, eget dapibus metus ante eu nisl. Quisque orci odio, interdum eu est sed, efficitur consectetur justo. Etiam ultrices, ligula ut feugiat aliquam, sem elit accumsan massa, a elementum ligula mi sed magna. Etiam et pharetra risus. Nullam a sapien tristique, blandit enim commodo, dictum justo. Fusce nec auctor massa. Sed luctus vitae felis vel imperdiet. Donec fringilla enim hendrerit, rhoncus erat in, posuere ligula. Maecenas hendrerit massa magna, pellentesque lobortis enim tristique non. Integer mollis quam id dictum interdum. Donec euismod mi quis ullamcorper dapibus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque justo nisi, elementum iaculis ornare eu, sodales non turpis. Cras quis orci non enim rhoncus facilisis. Etiam porttitor, lorem nec lacinia tincidunt, arcu felis lacinia enim, eget dapibus metus ante eu nisl. Quisque orci odio, interdum eu est sed, efficitur consectetur justo. Etiam ultrices, ligula ut feugiat aliquam, sem elit accumsan massa, a elementum ligula mi sed magna. Etiam et pharetra risus. Nullam a sapien tristique, blandit enim commodo, dictum justo. Fusce nec auctor massa. Sed luctus vitae felis vel imperdiet. Donec fringilla enim hendrerit, rhoncus erat in, posuere ligula. Maecenas hendrerit massa magna, pellentesque lobortis enim tristique non. Integer mollis quam id dictum interdum. Donec euismod mi quis ullamcorper dapibus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque justo nisi, elementum iaculis ornare eu, sodales non turpis. Cras quis orci non enim rhoncus facilisis. Etiam porttitor, lorem nec lacinia tincidunt, arcu felis lacinia enim, eget dapibus metus ante eu nisl. Quisque orci odio, interdum eu est sed, efficitur consectetur justo. Etiam ultrices, ligula ut feugiat aliquam, sem elit accumsan massa, a elementum ligula mi sed magna. Etiam et pharetra risus. Nullam a sapien tristique, blandit enim commodo, dictum justo. Fusce nec auctor massa. Sed luctus vitae felis vel imperdiet. Donec fringilla enim hendrerit, rhoncus erat in, posuere ligula. Maecenas hendrerit massa magna, pellentesque lobortis enim tristique non. Integer mollis quam id dictum interdum. Donec euismod mi quis ullamcorper dapibus.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque justo nisi, elementum iaculis ornare eu, sodales non turpis. Cras quis orci non enim rhoncus facilisis. Etiam porttitor, lorem nec lacinia tincidunt, arcu felis lacinia enim, eget dapibus metus ante eu nisl. Quisque orci odio, interdum eu est sed, efficitur consectetur justo. Etiam ultrices, ligula ut feugiat aliquam, sem elit accumsan massa, a elementum ligula mi sed magna. Etiam et pharetra risus. Nullam a sapien tristique, blandit enim commodo, dictum justo. Fusce nec auctor massa. Sed luctus vitae felis vel imperdiet. Donec fringilla enim hendrerit, rhoncus erat in, posuere ligula. Maecenas hendrerit massa magna, pellentesque lobortis enim tristique non. Integer mollis quam id dictum interdum. Donec euismod mi quis ullamcorper dapibus.</p>
    </div>
  );
}

export default ModalPage;
